version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MODE=${MODE:-wasm}
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}
    volumes:
      - backend_data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://192.168.1.6:8000}
        - VITE_DEFAULT_MODE=${MODE:-wasm}
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://192.168.1.6:8000}
      - VITE_DEFAULT_MODE=${MODE:-wasm}
    ports:
      - "5173:5173"
      - "5174:5174"
    depends_on:
      - backend

volumes:
  backend_data:
