[build]
  # Build the Vite app inside the frontend directory
  base = "frontend"
  command = "npm ci && npm run build"
  publish = "dist"

# SPA fallback: serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: if you host the Python backend separately and want to use a relative 
# path like /api from the frontend, uncomment and set your backend URL.
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-domain.example.com/:splat"
#   status = 200
#   force = true
